services:
  product-service:
    build: 
      context: ./ProductService
    ports:
      - "8001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=192.168.x.x,1433;Database=ProductDb;User=xxx;Password=xxx;Encrypt=False;
        
  order-service:
    build: 
      context: ./OrderService
    ports:
      - "8002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=192.168.100.x,1433;Database=OrderDb;User=xxx;Password=xxx;Encrypt=False;
       